server:
  address:     ":10088"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  accessLogEnabled: false
  errorLogEnabled: false
  DumpRouterMap : true

logger:
  path:    "logs/default"
  level:   "all"
  stdout:  true
  
database:
  default:
    link:   "pgsql:vben:yW8sWipJXa26Hnh5@tcp(114.115.157.254:5432)/vben"
#     link:  "mysql:vben:ZmdjwPdb3BBPsXhN@tcp(114.115.157.254:3306)/vben"
    debug:  true

