
gfcli:
  gen:
    dao:
#       - link:  "mysql:vben:yW8sWipJXa26Hnh5@tcp(114.115.157.254:3306)/vben"
      - link:   "pgsql:vben:yW8sWipJXa26Hnh5@tcp(114.115.157.254:5432)/vben"

  build:
    name: "gf-vben"
    arch: "amd64"
    system: "linux"
    version: "v1.0.0"
    path:   "./bin"
    extra: ""
